### ISSUE TITLE
How to use my custom script

### ISSUE THREAD

**Issue by prasenforu** [gree-gorey/bash-exporter#1]
I have my own shell script which gives output "OK" (0) or "NOTOK" (1) that I want to use as a metric value. Also use some metric " my_system_health".

my_system_health {host="hostname"} 1
my_system_health {host="hostname"} 0 

```
#!/bin/bash

hnm=`hostname`

  if [ `command` ]
  then
    result=1
  else
    result=0
  fi

 if [ $result=1 ]
  then
    my_system_health {host=$hnm} 1
  else
    my_system_health {host=$hnm} 0
  fi
```
Let me know how we can can configure, also Prometheus configuration.

Though it's not a issue but you may treat as use case.

**Comment by gree-gorey** [comment]
Hi @prasenforu 

Please use `2.0.0` version of exporter from Docker or from releases.

You can use a script like this:
```bash
#!/bin/bash

hnm=`hostname`

if [ true ]
then
  result=1
else
  result=0
fi

if [ $result=1 ]
then
  echo "{\"labels\": {\"host\": \"$hnm\"}, \"results\": {\"my_system_health\": 1} }"
else
  echo "{\"labels\": {\"host\": \"$hnm\"}, \"results\": {\"my_system_health\": 0} }"
fi

exit 0
```

And run `bash-exporter` like this, pointing to the folder with this script:
```console
$ ./bash-exporter -path ../scripts -labels host
```
Note the flag `-labels`. Here you must specify all the custom labels you want to use, comma-separated.

Then, your metrics will be available for Prometheus at `:9300`:
```console
$ curl 127.1:9300/metrics -s | grep ^bash
bash{host="my-hostname",job="job-3",verb="my_system_health"} 1
```

**Comment by prasenforu** [comment]
@gree-gorey 

Thanks for your valuable input ...

My target environment is Kubernetes and I want to use this script in a kubernetes ```configmap``` so I can modify as much as possible without pushing script inside the container and rebuild container.

I just need to confirm  that all scripts goes to ```/scripts/``` inside the container. right! 
And I can push multiple scripts...

one quick question is "bash" is default prefix for each  metric. 

is there anyway we can customized (as per my own choice)?

Let me deployed in my kubernetes cluster, may be will comeback again :)

**Comment by prasenforu** [comment]
@gree-gorey 

Looks like there are missing file job-3.sh in docker image version 2.0.0

**Comment by gree-gorey** [comment]
there was a problem with missing bash within the image, not script file
