### ISSUE TITLE
issue with example scripts

### ISSUE THREAD

**Issue by nico1106** [gree-gorey/bash-exporter#2]
I have the following example script:

```
#!/bin/sh

echo '{"labels": {"env": "dev"}, "results": {"items": 21} }'

exit 0
```

The exporter as docker container gives me the following error message:
json: cannot unmarshal object into Go value of type float64

Any suggestions?

**Comment by gree-gorey** [comment]
You most probably are using old version of exporter. Try using `2.0.0`. I updated the readme: https://github.com/gree-gorey/bash-exporter#docker-quick-start
