### ISSUE TITLE
Docker build not working - missing dependencies

### ISSUE THREAD

**Issue by lbayerlein** [gree-gorey/bash-exporter#6]
Hi,

thanks for your project. I am trying to change the CMD in your Dockerfile with the idea, to add parameters to the docker its (-interval for example).

Now I have cloned your repository and want to build my own docker image. Unfortunately this is failing with this error:

```
Sending build context to Docker daemon 2.048 kB
Step 1/10 : FROM golang:1.10.1
 ---> 1af690c44028
Step 2/10 : ENV https_proxy "https://proxy/"
 ---> Using cache
 ---> b873a2ddd91e
Step 3/10 : RUN go get -d -v github.com/gree-gorey/bash-exporter/cmd/bash-exporter
 ---> Running in 87be61fbf1ab

github.com/gree-gorey/bash-exporter (download)
github.com/prometheus/client_golang (download)
github.com/beorn7/perks (download)
github.com/cespare/xxhash (download)
package github.com/cespare/xxhash/v2: cannot find package "github.com/cespare/xxhash/v2" in any of:
        /usr/local/go/src/github.com/cespare/xxhash/v2 (from $GOROOT)
        /go/src/github.com/cespare/xxhash/v2 (from $GOPATH)
github.com/golang/protobuf (download)
github.com/prometheus/client_model (download)
github.com/prometheus/common (download)
github.com/matttproud/golang_protobuf_extensions (download)
github.com/prometheus/procfs (download)
The command '/bin/sh -c go get -d -v github.com/gree-gorey/bash-exporter/cmd/bash-exporter' returned a non-zero code: 1
```

I have checked this and xxhash is a dependency from the client_golang/prometheus repo and is an import from the registry.go file. Do you have an idea, how to solve this?

Thanks very much

**Comment by nanawel** [comment]
@lbayerlein Just try to replace
```Dockerfile
FROM golang:1.10.1
```
by
```Dockerfile
FROM golang:1.11
```
in the Dockerfile. (source: https://github.com/cespare/xxhash/issues/34#issuecomment-561905133)

You may want to use my fork which also fixes the missing `bash` package (#8): https://github.com/nanawel/bash-exporter

:warning: I cannot yet guarantee that this fork is 100% reliable. I'm still testing it.
